TextCorpusMVC/Controllers/TextController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using System.Windows.Documents;
using TextCorpusMVC.Models;

namespace TextCorpusMVC.Controllers
{
    [Authorize]
    public class TextController : Controller
    {
        

        private TextCorpusContext db = new TextCorpusContext();

        // GET: Text
        public ActionResult Index()
        {
            
            return View(db.TextSet.ToList());
        }

        // GET: Text/Details/5
        public ActionResult Details(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Text text = db.TextSet.First(x => x.Id == id);
            ViewBag.TagNames = new SelectList(
                db.TagSet.Include("Name").Where(x => x.TextId == id).Select(x => x.Name.Name).Distinct().ToList());
            ViewBag.TagsNum = text.TagSet.Count();
            var annotationStrings = text.Annotation.Split('\n');
            ViewBag.AnnotationStrings = annotationStrings;
            if (text == null)
            {
                return HttpNotFound();
            }
            return View(text);
        }

        [HttpPost, ActionName("HighlightText")]
        public ActionResult HighlightText(string tagToHighlight, int id)
        {
            var highlightedText = new HighlightedText();
            var text = db.TextSet.Include(x => x.TagSet.Select(tag => tag.Name)).Where(x => x.Id == id).First();
            highlightedText.Text = text;
            highlightedText.StartPositions = text.TagSet.Where(x => x.Name.Name == tagToHighlight).Select(x => x.StartPos).ToList();
            highlightedText.EndPositions = text.TagSet.Where(x => x.Name.Name == tagToHighlight).Select(x => x.EndPos).ToList();
            return PartialView(highlightedText);
        }

        //[HttpGet, ActionName("DownloadRtf")]
        public FileResult DownloadRtf(string tagToHighlight, int id)
        {
            int i =int.Parse(Request.Params["id"]);
            string t = Request.Params["tagToHighlight"];
            var text = db.TextSet.First(x => x.Id == id);
            var tags = db.TagSet.Include("Name").Where(x => x.TextId == id && x.Name.Name == tagToHighlight).ToList();
            var flowDoc = TextHighlighter.GetHighlightedText(text.Txt, tags);
            var range = new TextRange(flowDoc.ContentStart, flowDoc.ContentEnd);

            Directory.CreateDirectory(Server.MapPath("~/export/"));
            string fileName = text.Name + " c подсвеченными " + tagToHighlight + ".rtf";
            //fileName = fileName.Replace(' ', '_');
            fileName = Server.MapPath("~/export/" + fileName);

            FileStream fs = new FileStream(fileName, FileMode.Create, FileAccess.ReadWrite);
            range.Save(fs, DataFormats.Rtf);
            fs.Close();
            FileStream newFs = new FileStream(fileName, FileMode.Open, FileAccess.Read);

            fileName = text.Name + " c подсвеченными " + tagToHighlight + ".rtf";
            return File(newFs, "text/rtf", fileName);
        }


        // GET: Text/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Text/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase textUpload, HttpPostedFileBase annotationUpload, 
            [Bind(Include = "Name,Txt,Annotation, TextFile, AnnotationFile")] TextToUpload text)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    if (text.TextFile == null)
                    {
                        if (text.Txt == null)
                            text.Txt = string.Empty;
                    }
                    else if (Path.GetExtension(text.TextFile.FileName) != ".txt")
                    {
                        ModelState.AddModelError("", "Некорректное расширение файла с текстом. Загрузите файл с расширением .txt");
                        return View(text);
                    }
                    else
                    {
                        var sr = new StreamReader(text.TextFile.InputStream);
                        text.Txt = sr.ReadToEnd();
                        sr.Close();
                    }

                    if (text.AnnotationFile == null)
                    {
                        if (text.Annotation == null)
                            text.Annotation = string.Empty;
                    }
                    else if (Path.GetExtension(text.AnnotationFile.FileName) != ".ann")
                    {
                        ModelState.AddModelError("", "Некорректное расширение файла с аннотацией. Загрузите файл с расширением .ann");
                        return View(text);
                    }
                    else
                    {
                        var sr = new StreamReader(text.AnnotationFile.InputStream);
                        text.Annotation = sr.ReadToEnd();
                        sr.Close();
                    }

                    TextManager.UploadText(text.Txt, text.Annotation, text.Name);
                    return RedirectToAction("Index");
                }
                
            }
            catch (Exception /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Невозможно добавить текст. Проверьте правильность введенных данных.");
            }

            return View(text);
        }

        // GET: Text/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Text text = db.TextSet.Find(id);
            if (text == null)
            {
                return HttpNotFound();
            }
            return View(text);
        }

        // POST: Text/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var textToUpdate = db.TextSet.Find(id);
            var user = db.UserSet.First(x => x.Login == User.Identity.Name);

            if (!user.IsAdmin && !db.UserAccessSet.Any(x => x.UserId == user.Id && x.TextId == id))
            {
                ModelState.AddModelError("", "У вас нет доступа на редактирование этого текста");
                return View(textToUpdate);
            }
            string anno = ValueProvider.GetValue("Annotation").ConvertTo(typeof(string)).ToString();
            if (!TextManager.IsValidAnnotation(new StringReader(anno)))
            {
                ModelState.AddModelError("", "Некорректный формат аннотации");
                return View(textToUpdate);
            }
            if (TryUpdateModel(textToUpdate, "", new string[] { "Name", "Txt" }))
            {
                try
                {
                    db.SaveChanges();
                    var annotation = ValueProvider.GetValue("Annotation").ConvertTo(typeof(string)).ToString();
                    TextManager.UpdateTextAnnotation(id.Value, annotation);

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Невозможно сохранить изменения. Проверьте правильность введенных данных.");
                }
            }
            return View(textToUpdate);
        }

        // GET: Text/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Text text = db.TextSet.Find(id);

            var user = db.UserSet.First(x => x.Login == User.Identity.Name);
            if (!user.IsAdmin && !db.UserAccessSet.Any(x => x.UserId == user.Id && x.TextId == id))
            {
                return Content("<p class=\"text-warning\">Ошибка!<br/>У вас нет доступа на удаление этого текста</p>");
            }
            if (text == null)
            {
                return HttpNotFound();
            }
            return View(text);
        }

        // POST: Text/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Text text = db.TextSet.Find(id);
            
            db.TextSet.Remove(text);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TextCorpusMVC/Views/Text/Create.cshtml
@model TextCorpusMVC.Models.TextToUpload

@{
    ViewBag.Title = "Create";
}

<h2>Добавить текст</h2>


@using (Html.BeginForm("Create", "Text", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Название</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Текст</label>
            <div class="col-md-4">
                <textarea name="Txt" id="Txt" rows="10" cols="100" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Txt, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-2">
                <input type="file" name="TextFile" id="TextFile" value="Загрузить файл" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Аннотация</label>
            <div class="col-md-4">
                <textarea name="Annotation" id="Annotation" rows="10" cols="100" class="form-control"></textarea>
                @Html.ValidationMessageFor(model => model.Annotation, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-2">

                <input type="file" name="AnnotationFile" id="AnnotationFile" value="Загрузить файл" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TextCorpusMVC/Views/Text/Delete.cshtml
@model TextCorpusMVC.Models.Text

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>

<h3>Вы уверены что хотите удалить этот текст?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Текст
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Txt)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

TextCorpusMVC/Views/Text/Details.cshtml
@model TextCorpusMVC.Models.Text

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>

@using (Ajax.BeginForm("HighlightText", new AjaxOptions { UpdateTargetId = "highlightedText" }))
{
    <div>
        <div class="row">
            <div class="col-md-6">
                <h4>Текст</h4>
            </div>
            <div class="col-md-6">
                <h4>Аннотация</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <input name="id" hidden="hidden" value="@Model.Id" />
                @Html.DropDownList("tagToHighlight", (IEnumerable<SelectListItem>)ViewBag.TagNames,
                    htmlAttributes: new { style = "width: 100%", @class = "form-control", @onchange = "setLink()"})
                <br />
                <input type="submit" value="Подсветить" class="btn btn-default"/>
                <a href="/" name="downloadLink" OnClick="setLink()">Скачать</a>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6" id="highlightedText">
                @Html.DisplayFor(model => model.Txt)
            </div>
            <div class="col-md-offset-6">
                @foreach (var s in ViewBag.AnnotationStrings)
                {
                    @s
                    <br />
                }
            </div>
        </div>
    </div>
}
<div id="highlightedText"></div>
@Scripts.Render("~/scripts/jquery-1.10.2.min.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

TextCorpusMVC/Views/Text/Edit.cshtml
@model TextCorpusMVC.Models.Text

@{
    ViewBag.Title = "Edit";
}

<h2>Редактировать</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">Название</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Текст</label>
            <div class="col-md-4">
                <textarea name="Annotation" id="Annotation" rows="10" cols="100" class="form-control">@Model.Txt</textarea>
                @Html.ValidationMessageFor(model => model.Txt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Аннотация</label>
            <div class="col-md-4">
                <textarea name="Annotation" id="Annotation" rows="10" cols="100" class="form-control">@Model.Annotation</textarea>
                @Html.ValidationMessageFor(model => model.Annotation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TextCorpusMVC/Views/Text/HighlightText.cshtml
@model HighlightedText
<div id="highlightedText"> 
@{
    bool isHighlighted = false;
    for (int i = 0; i < Model.Text.Txt.Length; i++)
    {
        if (Model.StartPositions.Contains(i))
        {
            isHighlighted = true;
        }
        if (Model.EndPositions.Contains(i))
        {
            isHighlighted = false;
        }
        if (isHighlighted)
        {<span style="background-color : rgba(0, 193, 255, 0.71)">@Model.Text.Txt[i]</span>}
        else
        {@Model.Text.Txt[i]}
    }
}               
</div>

TextCorpusMVC/Views/Text/Index.cshtml
@model IEnumerable<TextCorpusMVC.Models.Text>

@{
    ViewBag.Title = "Index";
}

<h2>Список текстов</h2>

<p>
    @Html.ActionLink("Добавить текст", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Текст
        </th>
    </tr>

    @foreach (var item in Model)
     {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Txt)
            </td>
            <td>
                <ul style="list-style-type : none">
                    <li>@Html.ActionLink("Подробнее", "Details", new { id = item.Id })</li>
                    <li>@Html.ActionLink("Редактировать", "Edit", new { id = item.Id })</li>
                    <li>@Html.ActionLink("Удалить", "Delete", new { id = item.Id })</li>
                </ul>
            </td>

        </tr>
     }
</table>